[ALPS06334164] ANDROID: clang: update to 13.0.2
[Detail]
https://android-review.googlesource.com/c/kernel/common/+/1823999

[Solution]
1. replace r428724 to r433403
2. disable -Wunused-but-set-variable
3. fix error in sspm_timesync.c:174:37: error: overflow in expression;
result is 1385447424 with type long [-Werror,-Winteger-overflow]

MTK-Commit-Id: 7e87be8100d15ce2f0e44dbc3b1146197cf2d5a3

CR-Id: ALPS06334164
Feature: build process
Change-Id: I9be5fa9006f8bf535e24da3e52a919b09aa8d14d
Signed-off-by: Po Hu <po.hu@mediatek.com>